version: "3.8"
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:1.17.0"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -port 8000 -sharedDb"
  cli:
    depends_on:
      - dynamodb-local
    build:
      context: ./cli
    container_name: cli
    command: "/bin/sh ./create-table.sh"
  function:
    depends_on:
      - cli
    build:
      context: ./function
    container_name: function
    ports:
      - "9000:8080"
    environment:
      DYNAMODB_ENDPOINT: "http://dynamodb-local:8000"
